### ISSUE TITLE
TestWeightedFeatureEditDist.trivial2 is broken

### ISSUE THREAD

**Issue by sethtroisi** [dmort27/panphon#14]
```
def test_trivial2(self):
    self.assertGreater(self.dist.weighted_feature_edit_distance('ti', 'te'),
                       self.dist.weighted_feature_edit_distance('ti', 'tḭ'))

Traceback (most recent call last):
  File "/usr/local/google/home/sethtroisi/Projects/panphon/panphon/test/test_distance.py", line 71, in test_trivial2
    self.dist.weighted_feature_edit_distance('ti', 'tḭ'))
  File "/usr/local/google/home/sethtroisi/Projects/panphon/panphon/distance.py", line 615, in weighted_feature_edit_distance
    self.fm.word_to_vector_list(target, numeric=True, xsampa=xsampa))
  File "/usr/local/google/home/sethtroisi/Projects/panphon/panphon/featuretable.py", line 373, in word_to_vector_list
    tensor = [x.numeric() for x in segs]
  File "/usr/local/google/home/sethtroisi/Projects/panphon/panphon/featuretable.py", line 373, in <listcomp>
    tensor = [x.numeric() for x in segs]
AttributeError: 'NoneType' object has no attribute 'numeric'
```

Cause is related to the fact that 

```
def fts(self, ipa):
    if ipa in self.seg_dict:
        return self.seg_dict[ipa]
    else:
        return None

self.fts('ḭ') => None
None.numeric() => AttributeError
```

I'm not sure if 'ḭ' should appear in seg_dict, if word_tfs should filter out None segments or something else.

**Comment by dmort27** [comment]
This problem was introduced as a result of the (incomplete) transition to NFD. It should be resolved when the NFD problem is resolved.

**Comment by dmort27** [comment]
This appears to be fixed now.
